name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27' # Specify your preferred OTP version
          gleam-version: '1.17.0' # Specify your local Gleam version
          rebar3-version: '3.27.0'

      - name: Download Gleam dependencies
        run: gleam deps download

      - name: Build Lustre SPA
        run: gleam run -m lustre/dev build --minify

      - name: Correct and Verify Build Artifacts
        run: |
          cd dist
          sed -i 's_src="/_src="./_g' index.html
          sed -i 's_href="/_href="./_g' index.html
          cat index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true